# lastmod: 2019-08-04T10:00:36+02:00

alias cp='cp -i'
alias df='colourify df -h'
alias du='colourify du -h'
alias egrep='egrep --colour=auto'
alias firefox='firefox -P'
alias free='colourify free -h'
alias grep='grep --colour=auto'
alias ls='ls -l --human-readable --color=auto --group-directories-first'
alias more='less'
alias nmap='colourify nmap'
alias vi='vim'
