# load custom aliases
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# load grc aliasas
[[ -s '/etc/profile.d/grc.bashrc' ]] && source /etc/profile.d/grc.bashrc

# change sudoedit editor to vim
export SUDO_EDITOR=vim

# start tmnux automatically; see
# https://wiki.archlinux.org/index.php/Tmux#Start_tmux_on_every_shell_login
# for details
if [[ $DISPLAY ]]; then
    # If not running interactively, do not do anything
    [[ $- != *i* ]] && return
    [[ -z "$TMUX" ]] && exec tmux
fi
